<Project Sdk="Microsoft.NET.Sdk.Web">

  <!--<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>-->

<!--khushahal-->
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	
<!--local server-->

	<!--<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseAppHost>false</UseAppHost>
	</PropertyGroup>-->
<!--local server-->

	<ItemGroup>
	  <Compile Remove="Controllers\LiveRFQ\**" />
	  <Compile Remove="Views\QualityControl\Transaction\IncommingQCRMC\**" />
	  <Compile Remove="wwwroot\css\animate.css\**" />
	  <Compile Remove="wwwroot\js\classie\**" />
	  <Compile Remove="wwwroot\js\common\**" />
	  <Compile Remove="wwwroot\js\jquery-slimscroll\**" />
	  <Compile Remove="wwwroot\js\jquery-ui\**" />
	  <Compile Remove="wwwroot\js\modernizr\**" />
	  <Compile Remove="wwwroot\js\morris.js\**" />
	  <Compile Remove="wwwroot\js\raphael\**" />
	  <Compile Remove="wwwroot\pages\**" />
	  <Content Remove="Controllers\LiveRFQ\**" />
	  <Content Remove="Views\QualityControl\Transaction\IncommingQCRMC\**" />
	  <Content Remove="wwwroot\css\animate.css\**" />
	  <Content Remove="wwwroot\js\classie\**" />
	  <Content Remove="wwwroot\js\common\**" />
	  <Content Remove="wwwroot\js\jquery-slimscroll\**" />
	  <Content Remove="wwwroot\js\jquery-ui\**" />
	  <Content Remove="wwwroot\js\modernizr\**" />
	  <Content Remove="wwwroot\js\morris.js\**" />
	  <Content Remove="wwwroot\js\raphael\**" />
	  <Content Remove="wwwroot\pages\**" />
	  <EmbeddedResource Remove="Controllers\LiveRFQ\**" />
	  <EmbeddedResource Remove="Views\QualityControl\Transaction\IncommingQCRMC\**" />
	  <EmbeddedResource Remove="wwwroot\css\animate.css\**" />
	  <EmbeddedResource Remove="wwwroot\js\classie\**" />
	  <EmbeddedResource Remove="wwwroot\js\common\**" />
	  <EmbeddedResource Remove="wwwroot\js\jquery-slimscroll\**" />
	  <EmbeddedResource Remove="wwwroot\js\jquery-ui\**" />
	  <EmbeddedResource Remove="wwwroot\js\modernizr\**" />
	  <EmbeddedResource Remove="wwwroot\js\morris.js\**" />
	  <EmbeddedResource Remove="wwwroot\js\raphael\**" />
	  <EmbeddedResource Remove="wwwroot\pages\**" />
	  <None Remove="Controllers\LiveRFQ\**" />
	  <None Remove="Views\QualityControl\Transaction\IncommingQCRMC\**" />
	  <None Remove="wwwroot\css\animate.css\**" />
	  <None Remove="wwwroot\js\classie\**" />
	  <None Remove="wwwroot\js\common\**" />
	  <None Remove="wwwroot\js\jquery-slimscroll\**" />
	  <None Remove="wwwroot\js\jquery-ui\**" />
	  <None Remove="wwwroot\js\modernizr\**" />
	  <None Remove="wwwroot\js\morris.js\**" />
	  <None Remove="wwwroot\js\raphael\**" />
	  <None Remove="wwwroot\pages\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Models\Admin\Utilities\PostingParameterController.cs" />
	  <Compile Remove="Models\Admin\Utilities\PostingParameterListController.cs" />
	  <Compile Remove="Models\Admin\Utilities\PostingParameterSalaryController.cs" />
	  <Compile Remove="Models\Admin\Utilities\PostingParameterSalaryListController.cs" />
	  <Compile Remove="Models\Admin\Utilities\PostingParameterSalesController.cs" />
	  <Compile Remove="Models\Admin\Utilities\PostingParameterSalesListController.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\css\oldmasterstyle.css" />
	  <Content Remove="wwwroot\js\bootstrap-growl.min.js" />
	  <Content Remove="wwwroot\js\classie.js" />
	  <Content Remove="wwwroot\js\common-pages.js" />
	  <Content Remove="wwwroot\js\demo-12.js" />
	  <Content Remove="wwwroot\js\GlobalToaster.js" />
	  <Content Remove="wwwroot\js\GlobalValidation.js" />
	  <Content Remove="wwwroot\js\jquery.mCustomScrollbar.concat.min.js" />
	  <Content Remove="wwwroot\js\jquery.mousewheel.min.js" />
	  <Content Remove="wwwroot\js\Main.js" />
	  <Content Remove="wwwroot\js\pcoded.min.js" />
	  <Content Remove="wwwroot\js\SmoothScroll.js" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Views\GateEntry\Transaction\MiscConsumptionEntry\n2ahf43x.iif~" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.3.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CryptAndHash" Version="1.0.0" />
    <PackageReference Include="CryptSharp" Version="1.3.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="EPPlusFree" Version="4.5.3.8" />
    <PackageReference Include="itext7" Version="9.3.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
		
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="Spire.Doc" Version="14.2.7" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
		
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\FinancialAccounting\Accounting\" />
    <Folder Include="wwwroot\attachments\Purchase\" />
  
    <Folder Include="wwwroot\css\css\bootstrap\css\" />
    <Folder Include="wwwroot\css\css\images\" />
    <Folder Include="wwwroot\css\css\morris.js\css\" />
  </ItemGroup>

</Project>
