namespace travelexpensemanagement.Models.Purchase.Transiction
{
#nullable enable
    public class PURCHASE1
    {
        public int? YEAR_CODE { get; set; }
        public int? COMP_CODE { get; set; }
        public int? BRANCH_CODE { get; set; }
        public string? V_TYPE { get; set; }
        public int? V_NO { get; set; }
        public DateTime? V_DATE { get; set; }
        public string? DOC_ID { get; set; }
        public int? PLACE_CODE { get; set; }
        public int? EMP_CODE { get; set; }
        public int? PARTY_CODE { get; set; }
        public string? PARTY_NAME { get; set; }
        public decimal? EXCH_RATE { get; set; }
        public int? CREDIT_AC { get; set; }
        public int? DEBIT_AC { get; set; }
        public string? BILL_ADD1 { get; set; }
        public string? BILL_ADD2 { get; set; }
        public string? BILL_ADD3 { get; set; }
        public int? BILL_CITY { get; set; }
        public string? BILL_PINCODE { get; set; }
        public int? BILL_ADDRESSID { get; set; }
        public string? BILL_GST { get; set; }
        public int? SHIP_CODE { get; set; }
        public string? SHIP_ADD1 { get; set; }
        public string? SHIP_ADD2 { get; set; }
        public string? SHIP_ADD3 { get; set; }
        public int? SHIP_CITY { get; set; }
        public string? SHIP_PINCODE { get; set; }
        public int? SHIP_ADDRESSID { get; set; }
        public string? SHIP_GST { get; set; }
        public string? BILL_NO { get; set; }
        public DateTime? BILL_DATE { get; set; }
        public string? CHALL_NO { get; set; }
        public DateTime? CHALL_DATE { get; set; }
        public int? UOM_CODE { get; set; }
        public string? GATE_TYPE { get; set; }
        public int? GATE_NO { get; set; }
        public string? REF_TYPE { get; set; }
        public int? REF_NO { get; set; }
        public string? PASS_TYPE { get; set; }
        public int? PASS_NO { get; set; }
        public int? TRANSIT_NO { get; set; }
        public string? WAYBILL_NO { get; set; }
        public int? TRANSPORT_CODE { get; set; }
        public string? TRANSPORT_NAME { get; set; }
        public int? TRANSPORT_AC { get; set; }
        public string? GR_NO { get; set; }
        public DateTime? GR_DATE { get; set; }
        public string? TRUCK_NO { get; set; }
        public string? CONTAINER_NO { get; set; }
        public int? SEALED_VEHICLE { get; set; }
        public string? INPUT_TYPE { get; set; }
        public string? EXPS_TYPE { get; set; }
        public string? REMARKS { get; set; }
        public int? STATUS { get; set; }
        public decimal? RECD_QTY { get; set; }
        public decimal? BILL_QTY { get; set; }
        public decimal? AMOUNT { get; set; }
        public decimal? DISC_PER { get; set; }
        public decimal? DISC_AMT { get; set; }
        public decimal? PACK_PER { get; set; }
        public decimal? PACK_AMT { get; set; }
        public decimal? CGST_PER { get; set; }
        public decimal? CGST_AMT { get; set; }
        public decimal? SGST_PER { get; set; }
        public decimal? SGST_AMT { get; set; }
        public decimal? IGST_PER { get; set; }
        public decimal? IGST_AMT { get; set; }
        public decimal? CESS_PER { get; set; }
        public decimal? CESS_AMT { get; set; }
        public decimal? VAT_PER { get; set; }
        public decimal? VAT_AMT { get; set; }
        public decimal? OTH_AMT { get; set; }
        public decimal? TCS_PER { get; set; }
        public decimal? TCS_AMT { get; set; }
        public decimal? ROUND_OFF { get; set; }
        public decimal? NAMOUNT { get; set; }
        public decimal? DIFF_AMT { get; set; }
        public decimal? BANK_AMT { get; set; }
        public decimal? BANK_RATE { get; set; }
        public int? PL_NO { get; set; }
        public DateTime? PL_DATE { get; set; }
        public decimal? BILLAMT_USD { get; set; }
        public decimal? FRTPAY_AMT { get; set; }
        public decimal? FRTPAY_TAXPER { get; set; }
        public decimal? FRTPAY_TAX { get; set; }
        public string? FRTPAY_NAR { get; set; }
        public int? FRTPAY_DRAC { get; set; }
        public int? FRTPAY_CRAC { get; set; }
        public decimal? FRT_TDSPER { get; set; }
        public decimal? FRT_TDS { get; set; }
        public string? DR_FROM_TPT { get; set; }
        public int? TDS_ACT { get; set; }
        public decimal? TDS_PER { get; set; }
        public decimal? TDS_AMT { get; set; }
        public decimal? WB_AMT { get; set; }
        public decimal? WB_TDSPER { get; set; }
        public decimal? WB_TDS { get; set; }
        public int? WB_DRACT { get; set; }
        public int? WB_CRACT { get; set; }
        public string? WB_NARR { get; set; }
        public decimal? UL_AMT { get; set; }
        public decimal? UL_TDSPER { get; set; }
        public decimal? UL_TDS { get; set; }
        public int? UL_DRACT { get; set; }
        public int? UL_CRACT { get; set; }
        public string? UL_NARR { get; set; }
        public decimal? QLT_DR_AMT { get; set; }
        public decimal? QLT_DR_TAX { get; set; }
        public string? QLT_DR_NAR { get; set; }
        public decimal? QLT_CR_AMT { get; set; }
        public decimal? QLT_CR_TAX { get; set; }
        public string? QLT_CR_NAR { get; set; }
        public decimal? RDF_DR_AMT { get; set; }
        public decimal? RDF_DR_TAX { get; set; }
        public string? RDF_DR_NAR { get; set; }
        public decimal? RDF_CR_AMT { get; set; }
        public decimal? RDF_CR_TAX { get; set; }
        public string? RDF_CR_NAR { get; set; }
        public decimal? QTY_DR_AMT { get; set; }
        public decimal? QTY_DR_TAX { get; set; }
        public string? QTY_DR_NAR { get; set; }
        public decimal? QTY_CR_AMT { get; set; }
        public decimal? QTY_CR_TAX { get; set; }
        public string? QTY_CR_NAR { get; set; }
        public decimal? QC_DR_AMT { get; set; }
        public decimal? QC_DR_TAX { get; set; }
        public string? QC_DR_NAR { get; set; }
        public decimal? QC_CR_AMT { get; set; }
        public decimal? QC_CR_TAX { get; set; }
        public string? QC_CR_NAR { get; set; }
        public decimal? OTH_DR_AMT { get; set; }
        public decimal? OTH_DR_TAX { get; set; }
        public string? OTH_DR_NAR { get; set; }
        public string? QC_TYPE { get; set; }
        public int? QC_NO { get; set; }
        public int? DEPT_CODE { get; set; }
        public string? TAX_HOLD { get; set; }
        public string? PRICE_TYPE { get; set; }
        public string? FAPROV_STATUS { get; set; }
        public string? FAPROV_REMARKS { get; set; }
        public string? HOLD_PAY { get; set; }
        public string? HOLD_REASON { get; set; }
        public DateTime? HOLD_DATE { get; set; }
        public decimal? IMPORT_AMT { get; set; }
        public decimal? IMPORT_TAX { get; set; }
        public decimal? INVLAND_AMT { get; set; }
        public string? RCM_NO { get; set; }
        public int? DRNOTE_MAILSEND { get; set; }
        public int? FRT_BILLNO { get; set; }
        public DateTime? FRT_BILLDT { get; set; }
        public DateTime? FRT_PASSDT { get; set; }
        public string? FRT_CHQ { get; set; }
        public string? FRT_REMARK { get; set; }
        public int? GSTRMAIL_PARTYCNTR { get; set; }
        public int? GSTRMAIL_BILLCNTR { get; set; }
        public int? UUSER { get; set; }
        public DateTime? UDATE { get; set; }
        public int? EUSER { get; set; }
        public DateTime? EDATE { get; set; }
        public string? AED { get; set; }
        public string? WSID { get; set; }
        public string? LIP { get; set; }
        public string? LID { get; set; }
        public decimal? TDS_PER194Q { get; set; }
        public decimal? TDS_AMT194Q { get; set; }
        public string? DISP_ADDRESS { get; set; }
        public int? DISP_CITY { get; set; }
        public string? GSTRECO_REFTYPE { get; set; }
        public int? GSTRECO_REFNO { get; set; }
        public int? STOREIMG_FLG { get; set; }
        public string? RET_TYPE { get; set; }
        public decimal? FEXCH_USD { get; set; }
        public string? TRP_GSTNO { get; set; }
        public string? TRP_BILLNO { get; set; }
        public DateTime? TRP_BILLDATE { get; set; }
        public string? TRP_TAXTYPE { get; set; }
        public DateTime? MONTH_3B { get; set; }
        public DateTime? MONTH_3BN { get; set; }
        public DateTime? TRP_MONTH3B { get; set; }
        public string? MTH_REVYN3B { get; set; }
        public string? TRP_MTHREVYN3B { get; set; }
        public DateTime? MONTH_2B { get; set; }
        public DateTime? EWB_DATE { get; set; }
        public DateTime? EWB_EXPDATE { get; set; }
        public string? EWB_INVNO { get; set; }
        public decimal? PL_AMT { get; set; }

    }

}
